export interface StateDistricts {
  [state: string]: string[];
}

export const INDIAN_STATES_AND_DISTRICTS: StateDistricts = {
  'Haryana': [
    'Kurukshetra',
    'Ambala',
    'Bhiwani',
    'Charkhi Dadri',
    'Faridabad',
    'Fatehabad',
    'Gurugram',
    'Hisar',
    'Jhajjar',
    'Jind',
    'Kaithal',
    'Karnal',
    'Mahendragarh',
    'Nuh',
    'Palwal',
    'Panchkula',
    'Panipat',
    'Rewari',
    'Rohtak',
    'Sirsa',
    'Sonipat',
    'Yamunanagar',
  ],
  'Punjab': [
    'Amritsar',
    'Barnala',
    'Bathinda',
    'Faridkot',
    'Fatehgarh Sahib',
    'Fazilka',
    'Firozpur',
    'Gurdaspur',
    'Hoshiarpur',
    'Jalandhar',
    'Kapurthala',
    'Ludhiana',
    'Malerkotla',
    'Mansa',
    'Moga',
    'Mohali (SAS Nagar)',
    'Muktsar',
    'Pathankot',
    'Patiala',
    'Rupnagar',
    'Sangrur',
    'Shahid Bhagat Singh Nagar',
    'Tarn Taran',
  ],
  'Uttar Pradesh': [
    'Saharanpur',
    'Muzaffarnagar',
    'Shamli',
    'Meerut',
    'Baghpat',
    'Ghaziabad',
    'Hapur',
    'Gautam Buddha Nagar (Noida)',
    'Bulandshahr',
    'Aligarh',
    'Mathura',
    'Agra',
    'Moradabad',
    'Rampur',
    'Bijnor',
    'Bareilly',
    'Shahjahanpur',
    'Lucknow',
    'Kanpur Nagar',
    'Prayagraj (Allahabad)',
    'Varanasi',
    'Gorakhpur',
    'Ayodhya',
    'Jhansi',
    'Etawah',
  ],
  'Delhi NCR': [
    'Central Delhi',
    'East Delhi',
    'New Delhi',
    'North Delhi',
    'North East Delhi',
    'North West Delhi',
    'Shahdara',
    'South Delhi',
    'South East Delhi',
    'South West Delhi',
    'West Delhi',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Jhunjhunu',
    'Churu',
    'Sri Ganganagar',
    'Hanumangarh',
    'Nagaur',
    'Pali',
    'Barmer',
    'Dausa',
    'Sawai Madhopur',
    'Bhilwara',
    'Chittorgarh',
  ],
  'Himachal Pradesh': [
    'Bilaspur',
    'Chamba',
    'Hamirpur',
    'Kangra',
    'Kinnaur',
    'Kullu',
    'Lahaul and Spiti',
    'Mandi',
    'Shimla',
    'Sirmaur',
    'Solan',
    'Una',
  ],
  'Chandigarh (UT)': ['Chandigarh'],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Nainital',
    'Udham Singh Nagar',
    'Almora',
    'Pauri Garhwal',
    'Tehri Garhwal',
    'Chamoli',
    'Rudraprayag',
    'Uttarkashi',
    'Pithoragarh',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Munger',
    'Saharsa',
    'Samastipur',
    'Begusarai',
    'Nalanda',
    'Rohtas',
    'Bhojpur',
    'Siwan',
    'Saran',
    'Vaishali',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Gwalior',
    'Jabalpur',
    'Ujjain',
    'Sagar',
    'Satna',
    'Rewa',
    'Morena',
    'Bhind',
  ],
  'Jammu and Kashmir': [
    'Jammu',
    'Srinagar',
    'Kathua',
    'Udhampur',
    'Anantnag',
    'Baramulla',
    'Rajouri',
    'Samba',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Navi Mumbai',
  ],
  'Other State / UT': [
    'Other District',
  ],
};
